import { Button } from "@radix-ui/themes";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hello WOrld",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-bronze-5 flex min-h-screen flex-col items-center justify-between p-24">
      <Button color="plum">Mama</Button>
    </main>
  );
}
