import { supabase } from "@/lib/supabase";
import "@/styles/globals.css";
import { Button } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hello WOrld",
  description: "Generated by create next app",
};

const getUser = async () => {
  const { data } = await supabase.from("Users").select();
  console.log(data);
};

export default async function Home() {
  getUser();

  return (
    <main>
      <h2>Hello World</h2>
      <h3>Hello World</h3>
      <p>Hello World</p>
      <Button variant="contained">Hello</Button>
      <Button variant="text">Hello</Button>
    </main>
  );
}
