import "@/styles/globals.css";
import { Button } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hello WOrld",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <h1>Hello World</h1>
      <h2>Hello World</h2>
      <h3>Hello World</h3>
      <p>Hello World</p>
      <Button variant="contained">Hello</Button>
      <Button variant="text">Hello</Button>
    </main>
  );
}
